version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
      - ./db-init.sh:/db-init.sh
    entrypoint: /db-init.sh # 이게 없으면 init.sh가 실행안된다....왜지!??

volumes:
  mysql-data:
