name: Python application CI

on:
  push:
    branches: [ "feature/17-ci-yaml" ]
  pull_request:
    branches: [ "feature/17-ci-yaml" ]

permissions:
  contents: read

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install poetry
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: code-quality check
        run: |
          # @icehongssii flake, black 고쳐야할것들 발생하면 그 다음 명령어 중단됨 || true 임시로 추가
          poetry run flake8 . --max-line-length=120 --exclude=.git,build,dist,migrations,.venv --max-complexity=10 || true 
          poetry run black . --check || true
          poetry run isort . --check-only --profile black || true
      - name: Run Unit Tests
        run: |
          poetry run python -m pytest --junitxml=report.xml --cov=./ --cov-report=xml tests/unit tests/integration
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./report.xml
          fail_ci_if_error: true          