name: Python application CI

on:
  push:
    branches: [ "feature/17-ci-yaml" ]
  pull_request:
    branches: [ "feature/17-ci-yaml" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install
      - uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Upload virtual environment as artifact
        uses: actions/upload-artifact@v2
        with:
          name: venv
          path: .venv

  code-quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download virtual environment
        uses: actions/download-artifact@v2
        with:
          name: venv
          path: .venv
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Code Quality Checks
        run: |
          poetry run flake8 . --max-line-length=120 --exclude=.git,build,dist,migrations,.venv --max-complexity=10 --docstring-style=sphinx
          poetry run black . --check
          poetry run isort . --check-only --profile black
